### ISSUE TITLE
Nhi's progress on GSoC'24 tasks

### ISSUE THREAD

**Issue by nhintruong** [animint/animint2#136]
In this Github Issue, I will document my progress and status of my GSoC'24 tasks. 

06/19/2024 - 06/21/2024:
Porting Visualization Gallery Task:
I worked through the rest of the visualization gallery, ported the accessible figures while skipped any duplicates

- My pull request:  https://github.com/animint/gallery/pull/4

This PR includes all the figures I have ported thus far. Howerver, multiple visualizations in a single PR may cause preview difficulties so I will include only one data viz at a time in future PRs

- I have a Github Issue about my problems:  https://github.com/animint/gallery/issues/5

**Comment by nhintruong** [comment]
06/23/2024: 

1. Porting Visualization Gallery Task:

- I've encountered some challenges due to missing files, which I mentioned in our current meeting. To address this, I've created GitHub Issue in the repository of each source code and mentioned Toby for guidance. 
 tdhock/sandia-enrollment/issues/1 
tdhock/species-variable-selection/issues/1

2. Chromote Testing Task: 

- I've updated the workflow in my repository which I forked from animint/animint 2, transitioning the use of Firefox (which I initially believed to be PhantomJS) to Chrome. 
- After running the updated workflow, I identified 3 test suites that failed. Please find the results of each test suite below:

Test Suite renderer1 (FAIL 25 | WARN 0 | SKIP 0 | PASS 427) 
![image](https://github.com/animint/animint2/assets/102540257/e0f4e41e-e41d-497b-bdb0-d61b31eeb5a5)

Test Suite renderer2 (FAIL 11 | WARN 0 | SKIP 0 | PASS 185)
![image](https://github.com/animint/animint2/assets/102540257/0f1c17e5-abe1-4452-a92e-92ab0fedc0a2)

Test Suite renderer3 (FAIL 7 | WARN 0 | SKIP 0 | PASS 66)
![image](https://github.com/animint/animint2/assets/102540257/c9ca9711-8cbb-4072-ae59-273ec9911024)

**Comment by nhintruong** [comment]
24/06/2025 

1. Porting Visualization Gallery Task: I've created some GitHub issues in the respective repositories due to missing files or data errors bellow:
- [ ] tdhock/max-generalized-auc/issues/4
- [ ] tdhock/changepoint-data-structure/issues/1
- [ ] tdhock/hla-asthma/issues/1
2. Automatically capture screenshots for animint2pages function.

I'm trying to find the suitable approach to implement automatic screenshot capture for the animint2pages function using Webshot. While I'm not yet familiar with Webshot and its screenshot capabilities, I am trying to learn its suitability with the task.

**Comment by tdhock** [comment]
instead of posting screenshots/images of text results, please copy the relevant text into an issue comment, which makes it easier to understand and search.
You wrote "I've updated the workflow in my repository..." but why did you do that?
We wanted to know if the chromote testing works on your personal computer, not on your github actions.
About the automatic screenshot, please work with @siddhesh195 who has already started work on that in #131

**Comment by nhintruong** [comment]
> instead of posting screenshots/images of text results, please copy the relevant text into an issue comment, which makes it easier to understand and search. You wrote "I've updated the workflow in my repository..." but why did you do that? We wanted to know if the chromote testing works on your personal computer, not on your github actions. About the automatic screenshot, please work with @siddhesh195 who has already started work on that in #131

Hi, I've updated the github workflow as per our initial collaboration plan (https://github.com/animint/animint2/issues/129). It's my negligence not to check Siddhesh's progress beforehand, as I was unaware he had completed this task. 

Regarding Chromote testing, I had an email to Siddhesh asking about Chromote testing task on Linux, and he informed me that he's finished the Linux-related work, so that's no longer on my agenda. 

I am going to have a meeting with Siddhesh soon to discuss the enhancing the animint2pages function task.

**Comment by nhintruong** [comment]
25/05/2024 - 26/06/2024: 

I created the list of non-portable viz data: https://github.com/animint/gallery/issues/7, I am adjusting data viz based on  comments in PR https://github.com/animint/gallery/pull/4

**Comment by nhintruong** [comment]
27/06/2024: 
About enhancing the animint2pages function task: I started the work of study ImagineMagick for cropping whitespace around plots

**Comment by tdhock** [comment]
Hi again Nhi
I have asked verbally and in writing for daily updates about what you have been working on.
I expected you to write in issues/PRs at least once every day. 
But I still do not see any progress updates.
If you can't start doing that in the next few days, you will fail GSOC mid-term evals.

**Comment by Faye-yufan** [comment]
> 27/06/2024: About enhancing the animint2pages function task: I started the work of study ImagineMagick for cropping whitespace around plots

Hi @nhintruong , do you have any updates on this task? Whatever you found about ImagineMagick you can post it here. You can also create a draft PR, it is not necessarily for others to review, but it can show the community about your progress.

**Comment by nhintruong** [comment]
> Hi again Nhi I have asked verbally and in writing for daily updates about what you have been working on. I expected you to write in issues/PRs at least once every day. But I still do not see any progress updates. If you can't start doing that in the next few days, you will fail GSOC mid-term evals.

I sincerely apologize for my recent lack of communication and work delays. I recently attended a Robotics workshop in Austria, which required more preparation time than expected. I ran source code for data visualizations and documented errors but failed to report them promptly. I acknowledge my insufficient time commitment to GSoC and take full responsibility for my shortcomings. I humbly hope for an opportunity to implement better time management and maintain more frequent communication. This project is immensely valuable to me, and I'm grateful for the experience gained. I hope to rectify my mistakes and contribute more meaningfully.

**Comment by nhintruong** [comment]
01/07 - 04/07: 

 I  worked on visualizations 25th-35th but encountered challenges that prevented PR submission. I've documented these issues reported about the problem:
https://github.com/tdhock/temperature-sensor/issues/1
https://github.com/tdhock/mmit-paper/issues/2
https://github.com/tdhock/PeakSegFPOP-paper/issues/2
https://github.com/tdhock/PeakSegFPOP/issues/7
https://github.com/tdhock/PeakSegFPOP-paper/issues/3
https://github.com/tdhock/animint-examples/issues/2

**Comment by nhintruong** [comment]
06/07/2024
Given the persistent errors, I've decided to focus on troubleshooting rather than proceeding with additional source code as this approach will be more productive in the long run.

**Comment by nhintruong** [comment]
09/07/2024 
I tried to update new data viz but facing problem: I've forked the gallery and updated the [repos.txt](https://github.com/nhintruong/gallery/blob/gh-pages/repos.txt) file, but the data visualization hasn't updated accordingly.
 

My pull request: https://github.com/animint/gallery/pull/10
